version: 2.1
#cfn-lintのREADME↓でPythonは3.7以上を指定しているのでOrbは使用せず
#https://github.com/aws-cloudformation/cfn-lint
# orbs:
#   python: circleci/python@2.0.3
jobs:
  cfn-lint:
    # executor: python/default　実行環境としてOrb由来使わずDockerイメージを使うので無効化
    docker:
      - image: cimg/python:3.12.0

    steps:
      - checkout
      - run: python --version
      - run: pip install cfn-lint
      - run:
          name: run cfn-lint
          command: |
            cfn-lint -i W3010 -t lecture10_CFnTemplate/*.yml

workflows:
  raisetech:
    jobs:
      - cfn-lint
